# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7c88278e9e4b5d496cb4ba528cc3ec77d704613b489f2458254c34f167d4d7633d05497bd57bff87818217f7d67125a05823e87b946198d1ace430077b8618d

test:
  secret_key_base: bf80708a80c27e16bf07852305b3dda76a439b99e3e2cf0f3a2e341c205b6638e48f74950e18b0dad19a18334c2155f0bb01ba0bfb4a55a4d07e9809143a4bcc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
